#!/bin/bash
set -e
echo lösche de_junious
userdel -r de_junious
echo lösche nunez_gomez
userdel -r nunez_gomez
echo lösche ullagoss
userdel -r ullagoss
echo lösche lanpher
userdel -r lanpher
echo lösche galvin
userdel -r galvin
echo lösche laspina
userdel -r laspina
echo lösche dodich
userdel -r dodich
echo lösche bannowsky
userdel -r bannowsky
echo lösche waisath
userdel -r waisath
echo lösche von_reddig-piette
userdel -r von_reddig-piette
echo lösche latona
userdel -r latona
echo lösche homewood
userdel -r homewood
echo lösche pallafor-zedian
userdel -r pallafor-zedian
echo lösche senemounnarat-quillian
userdel -r senemounnarat-quillian
echo lösche isaac
userdel -r isaac
echo lösche plancarte
userdel -r plancarte
echo lösche berteotti-stirn
userdel -r berteotti-stirn
echo lösche strycker
userdel -r strycker
echo lösche von_verrill
userdel -r von_verrill
echo lösche deschner
userdel -r deschner
echo lösche franzi
userdel -r franzi
echo lösche cringle
userdel -r cringle
echo lösche kosh
userdel -r kosh
echo lösche derouchie
userdel -r derouchie
echo lösche doutt
userdel -r doutt
echo lösche munley
userdel -r munley
echo lösche dornbos
userdel -r dornbos
echo lösche mahala
userdel -r mahala
echo lösche ellingwood
userdel -r ellingwood
echo lösche de_cardinalli-sciola
userdel -r de_cardinalli-sciola
echo lösche gundry
userdel -r gundry
echo lösche pinedo
userdel -r pinedo
echo lösche faivre
userdel -r faivre
echo lösche pinsky
userdel -r pinsky
echo lösche 1pinsky
userdel -r 1pinsky
echo lösche 2pinsky
userdel -r 2pinsky
echo lösche 3pinsky
userdel -r 3pinsky
echo lösche norlien
userdel -r norlien
echo lösche preato
userdel -r preato
